### ISSUE TITLE
testing in wild and result size

### ISSUE THREAD

**Issue by ghost** [fjxmlzn/InfoGAN-CR#2]
can you provide how to test on your own images for the celeba pretrained model and the results sizes are really small and hard to see the difference currently

**Comment by fjxmlzn** [comment]
Sorry what do you mean by "test on your own images for the celeba pretrained model"? Do you want to run InfoGAN-CR on your own image dataset, or something else?

And what do you mean by "results sizes"?

**Comment by ghost** [comment]
@fjxmlzn I mean like testing on a single image like this one 
![rdjtest2](https://user-images.githubusercontent.com/6818285/59722688-994dc700-9224-11e9-9b14-2fbed4579a6b.jpeg)

I mean the current result grid is very small for each latent result like 32x32 for each one and you cant see it clearly
![sample23](https://user-images.githubusercontent.com/6818285/59722738-c13d2a80-9224-11e9-92ee-74b3a23728ba.png)

**Comment by fjxmlzn** [comment]
This is because this pre-trained model was trained on 32x32 CelebA. If you want to generate images of higher resolution, just change the training data to whatever you want and retrain the model.

**Comment by ghost** [comment]
@fjxmlzn ok also you can test on single image instead of whole dataset?

**Comment by fjxmlzn** [comment]
This InfoGAN-CR is for generating images and is required to train on many images (same as other GANs). Sorry I don't know what you mean by "test on single image". Could you please clarify more on that?

Do you mean changing the factors of a single given image?
