### ISSUE TITLE
MIG mutual information gap?

### ISSUE THREAD

**Issue by sharonzhou** [fjxmlzn/InfoGAN-CR#3]
How well do you perform on dSprites using the mutual information gap (MIG)? I'd expect this to do well, so would love to see results.

**Comment by fjxmlzn** [comment]
Hi, I just uploaded our code for computing MIG, FactorVAE metric, BetaVAE metric, SAP, Explicitness, Modularity, DCI, and dHSIC. The instructions on how to use it are in README. The metric numbers we get will soon be available in ICML camera ready.

**Comment by fjxmlzn** [comment]
We have just updated the metric numbers (including MIG) in the arxiv version: https://arxiv.org/abs/1906.06034. It is also available in the readme.
